
categories = {
    'actions': "General action-oriented cards",
    'adjectives': "Cards with descriptive words",
    'clothes': "Cards related to clothing items and dressing actions",
    'communication': "Cards for basic expressions, requests, and emotions",
    'education': "Cards for educational and school-related items and actions",
    'emotions': "Cards for emotional expressions",
    'family': "Cards for family relationships",
    'food meals': "Cards related to food items, flavors, and eating actions",
    'health': "Cards for medical-related actions and items",
    'holidays': "Cards representing holiday-related activities and items",
    'household': "Cards related to daily activities and routine items",
    'hygiene': "Cards for hygiene routines",
    'numbers quantity': "Cards related to numbers and quantities",
    'pandemics': "Cards related to health safety during pandemics",
    'pronouns': "Cards for pronouns",
    'signals': "Cards for signals and instructions"
}

cards = {
"adjectives_____wet___deti.svg": {"category": "adjectives", "keywords": "wet", "target": "kids"},
"education_____write___deti.svg": {"category": "education", "keywords": "write", "target": "kids"},
"actions_____talk___dorosli.svg": {"category": "actions", "keywords": "talk", "target": "adults"},
"numbers_quantity_____five___deti.svg": {"category": "numbers quantity", "keywords": "five", "target": "kids"},
"education_____board___deti.svg": {"category": "education", "keywords": "board", "target": "kids"},
"pandemics_____infected___dorosli.svg": {"category": "pandemics", "keywords": "infected", "target": "adults"},
"education_____break___deti.svg": {"category": "education", "keywords": "break", "target": "kids"},
"communication_____thank_you___deti.svg": {"category": "communication", "keywords": "thank you", "target": "kids"},
"hygene_____comb_hair___dorosli.svg": {"category": "hygiene", "keywords": "comb hair", "target": "adults"},
"food_meals_____salt___deti.svg": {"category": "food meals", "keywords": "salt", "target": "kids"},
"health_____hurts___dorosli.svg": {"category": "health", "keywords": "hurts", "target": "adults"},
"signals_____get_back___deti.svg": {"category": "signals", "keywords": "get back", "target": "kids"},
"pandemics_____virus___dorosli.svg": {"category": "pandemics", "keywords": "virus", "target": "adults"},
"food_meals_____soup___deti.png": {"category": "food meals", "keywords": "soup", "target": "kids"},
"holidays_____santa_claus___deti.svg": {"category": "holidays", "keywords": "santa claus", "target": "kids"},
"adjectives_____younger___deti.svg": {"category": "adjectives", "keywords": "younger", "target": "kids"},
"numbers_quantity_____seven___deti.svg": {"category": "numbers quantity", "keywords": "seven", "target": "kids"},
"pronouns_____how___dorosli.svg": {"category": "pronouns", "keywords": "how", "target": "adults"},
"pronouns_____where___dorosli.svg": {"category": "pronouns", "keywords": "where", "target": "adults"},
"clothes_____clothes___deti.svg": {"category": "clothes", "keywords": "clothes", "target": "kids"},
"communication_____communicate___deti.svg": {"category": "communication", "keywords": "communicate", "target": "kids"},
"emotions_____frightened___deti.svg": {"category": "emotions", "keywords": "frightened", "target": "kids"},
"pandemics_____hard_to_breathe___dorosli.svg": {"category": "pandemics", "keywords": "hard to breathe", "target": "adults"},
"hygene_____wash_hands___dorosli.svg": {"category": "hygiene", "keywords": "wash hands", "target": "adults"},
"actions_____take___deti.svg": {"category": "actions", "keywords": "take", "target": "kids"},
"family_____sister___dorosli.svg": {"category": "family", "keywords": "sister", "target": "adults"},
"actions_____can_not___deti.svg": {"category": "actions", "keywords": "can not", "target": "kids"},
"actions_____drink___dorosli.svg": {"category": "actions", "keywords": "drink", "target": "adults"},
"education_____answer___deti.svg": {"category": "education", "keywords": "answer", "target": "kids"},
"communication_____do_not_understand___dorosli.svg": {"category": "communication", "keywords": "do not understand", "target": "adults"},
"actions_____jamp___deti.svg": {"category": "actions", "keywords": "jamp", "target": "kids"},
"actions_____walk___deti.svg": {"category": "actions", "keywords": "walk", "target": "kids"},
"food_meals_____sour___deti.svg": {"category": "food meals", "keywords": "sour", "target": "kids"},
"health_____logoped___dorosli.svg": {"category": "health", "keywords": "logoped", "target": "adults"},
"signals_____stop___deti.svg": {"category": "signals", "keywords": "stop", "target": "kids"},
"pandemics_____dirty_hands___dorosli.svg": {"category": "pandemics", "keywords": "dirty hands", "target": "adults"},
"actions_____sit___deti.svg": {"category": "actions", "keywords": "sit", "target": "kids"},
"education_____get_calm___deti.svg": {"category": "education", "keywords": "get calm", "target": "kids"},
"household_____shop___dorosli.svg": {"category": "household", "keywords": "shop", "target": "adults"},
"health_____ill___deti.svg": {"category": "health", "keywords": "ill", "target": "kids"},
"communication_____stop___deti.svg": {"category": "communication", "keywords": "stop", "target": "kids"},
"numbers_quantity_____one___deti.svg": {"category": "numbers quantity", "keywords": "one", "target": "kids"},
"pandemics_____wash_hands___dorosli.svg": {"category": "pandemics", "keywords": "wash hands", "target": "adults"},
"communication_____no___dorosli.svg": {"category": "communication", "keywords": "no", "target": "adults"},
"food_meals_____eat___deti.svg": {"category": "food meals", "keywords": "eat", "target": "kids"},
"holidays_____decorate___deti.svg": {"category": "holidays", "keywords": "decorate", "target": "kids"},
"hygene_____toilet___dorosli.svg": {"category": "hygiene", "keywords": "toilet", "target": "adults"},
"adjectives_____common___deti.svg": {"category": "adjectives", "keywords": "common", "target": "kids"},
"signals_____call_my_family___deti.svg": {"category": "signals", "keywords": "call my family", "target": "kids"},
"emotions_____do_not_like___deti.svg": {"category": "emotions", "keywords": "do not like", "target": "kids"},
"pronouns_____me___dorosli.svg": {"category": "pronouns", "keywords": "me", "target": "adults"},
"actions_____sit___dorosli.svg": {"category": "actions", "keywords": "sit", "target": "adults"},
"education_____walk___deti.svg": {"category": "education", "keywords": "walk", "target": "kids"},
"hygene_____rinse_mouth___dorosli.svg": {"category": "hygiene", "keywords": "rinse mouth", "target": "adults"},
"health_____hurts___deti.svg": {"category": "health", "keywords": "hurts", "target": "kids"},
"health_____nurse___dorosli.svg": {"category": "health", "keywords": "nurse", "target": "adults"},
"hygene_____brush_teeth___deti.svg": {"category": "hygiene", "keywords": "brush teeth", "target": "kids"},
"holidays_____gift___deti.svg": {"category": "holidays", "keywords": "gift", "target": "kids"},
"communication_____good___dorosli.svg": {"category": "communication", "keywords": "good", "target": "adults"},
"actions_____play___deti.svg": {"category": "actions", "keywords": "play", "target": "kids"},
"education_____study___deti.svg": {"category": "education", "keywords": "study", "target": "kids"},
"hygene_____wipe___deti.svg": {"category": "hygiene", "keywords": "wipe", "target": "kids"},
"hygene_____rinse_mouth___deti.svg": {"category": "hygiene", "keywords": "rinse mouth", "target": "kids"},
"numbers_quantity_____three___deti.svg": {"category": "numbers quantity", "keywords": "three", "target": "kids"},
"numbers_quantity_____a_little___deti.svg": {"category": "numbers quantity", "keywords": "a little", "target": "kids"},
"emotions_____like___deti.svg": {"category": "emotions", "keywords": "like", "target": "kids"},
"education_____ask___deti.svg": {"category": "education", "keywords": "ask", "target": "kids"},
"actions_____dance___deti.svg": {"category": "actions", "keywords": "dance", "target": "kids"},
"pronouns_____our___deti.svg": {"category": "pronouns", "keywords": "our", "target": "kids"},
"actions_____listen___deti.svg": {"category": "actions", "keywords": "listen", "target": "kids"},
"education_____school___deti.svg": {"category": "education", "keywords": "school", "target": "kids"},
"family_____you___dorosli.svg": {"category": "family", "keywords": "you", "target": "adults"},
"communication_____bye___deti.svg": {"category": "communication", "keywords": "bye", "target": "kids"},
"actions_____clean___deti.svg": {"category": "actions", "keywords": "clean", "target": "kids"},
"emotions_____tired___deti.svg": {"category": "emotions", "keywords": "tired", "target": "kids"},
"numbers_quantity_____nine___deti.svg": {"category": "numbers quantity", "keywords": "nine", "target": "kids"},
"education_____must___deti.svg": {"category": "education", "keywords": "must", "target": "kids"},
"family_____you___deti.svg": {"category": "family", "keywords": "you", "target": "kids"},
"family_____father___deti.svg": {"category": "family", "keywords": "father", "target": "kids"},
"health_____medicines___deti.svg": {"category": "health", "keywords": "medicines", "target": "kids"},
"food_meals_____cereals___deti.png": {"category": "food meals", "keywords": "cereals", "target": "kids"},
"holidays_____new_year_tree___deti.svg": {"category": "holidays", "keywords": "new year tree", "target": "kids"},
"health_____fever___deti.svg": {"category": "health", "keywords": "fever", "target": "kids"},
"emotions_____dont_want___deti.svg": {"category": "emotions", "keywords": "dont want", "target": "kids"},
"pandemics_____quarantine___dorosli.svg": {"category": "pandemics", "keywords": "quarantine", "target": "adults"},
"family_____grandfather___dorosli.svg": {"category": "family", "keywords": "grandfather", "target": "adults"},
"communication_____hello___deti.svg": {"category": "communication", "keywords": "hello", "target": "kids"},
"communication_____give___dorosli.svg": {"category": "communication", "keywords": "give", "target": "adults"},
"education_____do___deti.svg": {"category": "education", "keywords": "do", "target": "kids"},
"emotions_____joyful___dorosli.svg": {"category": "emotions", "keywords": "joyful", "target": "adults"},
"emotions_____joyful___deti.svg": {"category": "emotions", "keywords": "joyful", "target": "kids"},
"actions_____do_not_like___dorosli.svg": {"category": "actions", "keywords": "do not like", "target": "adults"},
"communication_____yes___dorosli.svg": {"category": "communication", "keywords": "yes", "target": "adults"},
"health_____stay_at_hospital___dorosli.svg": {"category": "health", "keywords": "stay at hospital", "target": "adults"},
"adjectives_____light___dorosli.svg": {"category": "adjectives", "keywords": "light", "target": "adults"},
"actions_____gather___deti.svg": {"category": "actions", "keywords": "gather", "target": "kids"},
"adjectives_____hot___deti.svg": {"category": "adjectives", "keywords": "hot", "target": "kids"},
"hygene_____wash_hands___deti.svg": {"category": "hygiene", "keywords": "wash hands", "target": "kids"},
"family_____grandmother___deti.svg": {"category": "family", "keywords": "grandmother", "target": "kids"},
"communication_____not_allowed___deti.svg": {"category": "communication", "keywords": "not allowed", "target": "kids"},
"family_____man___dorosli.svg": {"category": "family", "keywords": "man", "target": "adults"},
"pandemics_____cough___dorosli.svg": {"category": "pandemics", "keywords": "cough", "target": "adults"},
"holidays_____greet___deti.svg": {"category": "holidays", "keywords": "greet", "target": "kids"},
"family_____I___dorosli.svg": {"category": "family", "keywords": "I", "target": "adults"},
"actions_____look___deti.svg": {"category": "actions", "keywords": "look", "target": "kids"},
"emotions_____angry___deti.svg": {"category": "emotions", "keywords": "angry", "target": "kids"},
"household_____work___dorosli.svg": {"category": "household", "keywords": "work", "target": "adults"},
"adjectives_____cold___deti.svg": {"category": "adjectives", "keywords": "cold", "target": "kids"},
"health_____doctor_woman___deti.svg": {"category": "health", "keywords": "doctor woman", "target": "kids"},
"family_____wife___dorosli.svg": {"category": "family", "keywords": "wife", "target": "adults"},
"actions_____give___deti.svg": {"category": "actions", "keywords": "give", "target": "kids"},
"communication_____no___deti.svg": {"category": "communication", "keywords": "no", "target": "kids"},
"adjectives_____older___deti.svg": {"category": "adjectives", "keywords": "older", "target": "kids"},
"education_____teacher_woman___deti.svg": {"category": "education", "keywords": "teacher woman", "target": "kids"},
"adjectives_____barbed___deti.svg": {"category": "adjectives", "keywords": "barbed", "target": "kids"},
"pandemics_____stay_in_bed___dorosli.svg": {"category": "pandemics", "keywords": "stay in bed", "target": "adults"},
"actions_____lay___deti.svg": {"category": "actions", "keywords": "lay", "target": "kids"},
"communication_____wait___deti.svg": {"category": "communication", "keywords": "wait", "target": "kids"},
"actions_____eat___dorosli.svg": {"category": "actions", "keywords": "eat", "target": "adults"},
"pronouns_____their___deti.svg": {"category": "pronouns", "keywords": "their", "target": "kids"},
"actions_____speak___deti.svg": {"category": "actions", "keywords": "speak", "target": "kids"},
"actions_____lay___dorosli.svg": {"category": "actions", "keywords": "lay", "target": "adults"},
"family_____daughter___dorosli.svg": {"category": "family", "keywords": "daughter", "target": "adults"},
"health_____body_temperature___deti.svg": {"category": "health", "keywords": "body temperature", "target": "kids"},
"emotions_____sad___dorosli.svg": {"category": "emotions", "keywords": "sad", "target": "adults"},
"pandemics_____avoid_public_places___dorosli.svg": {"category": "pandemics", "keywords": "avoid public places", "target": "adults"},
"pandemics_____fever___dorosli.svg": {"category": "pandemics", "keywords": "fever", "target": "adults"},
"health_____injection___deti.svg": {"category": "health", "keywords": "injection", "target": "kids"},
"communication_____bad___dorosli.svg": {"category": "communication", "keywords": "bad", "target": "adults"},
"actions_____can___deti.svg": {"category": "actions", "keywords": "can", "target": "kids"},
"signals_____do_not_touch___deti.svg": {"category": "signals", "keywords": "do not touch", "target": "kids"},
"numbers_quantity_____eight___deti.svg": {"category": "numbers quantity", "keywords": "eight", "target": "kids"},
"household_____toys___deti.svg": {"category": "household", "keywords": "toys", "target": "kids"},
"emotions_____tired___dorosli.svg": {"category": "emotions", "keywords": "tired", "target": "adults"},
"education_____teacher_man___deti.svg": {"category": "education", "keywords": "teacher man", "target": "kids"},
"pronouns_____I___deti.svg": {"category": "pronouns", "keywords": "I", "target": "kids"},
"hygene_____wash_body___deti.svg": {"category": "hygiene", "keywords": "wash body", "target": "kids"},
"numbers_quantity_____several___deti.svg": {"category": "numbers quantity", "keywords": "several", "target": "kids"},
"communication_____great___deti.svg": {"category": "communication", "keywords": "great", "target": "kids"},
"hygene_____toilet___deti.svg": {"category": "hygiene", "keywords": "toilet", "target": "kids"},
"actions_____show___deti.svg": {"category": "actions", "keywords": "show", "target": "kids"},
"health_____hospital___deti.svg": {"category": "health", "keywords": "hospital", "target": "kids"},
"emotions_____do_not_want___deti.svg": {"category": "emotions", "keywords": "do not want", "target": "kids"},
"food_meals_____sweet___deti.svg": {"category": "food meals", "keywords": "sweet", "target": "kids"},
"hygene_____wash_face___deti.svg": {"category": "hygiene", "keywords": "wash face", "target": "kids"},
"actions_____rest___deti.svg": {"category": "actions", "keywords": "rest", "target": "kids"},
"actions_____go___dorosli.svg": {"category": "actions", "keywords": "go", "target": "adults"},
"food_meals_____bitter___dorosli.svg": {"category": "food meals", "keywords": "bitter", "target": "adults"},
"health_____doctor_man___deti.svg": {"category": "health", "keywords": "doctor man", "target": "kids"},
"emotions_____love___deti.svg": {"category": "emotions", "keywords": "love", "target": "kids"},
"hygene_____wash_face___dorosli.svg": {"category": "hygiene", "keywords": "wash face", "target": "adults"},
"holidays_____surprise___deti.svg": {"category": "holidays", "keywords": "surprise", "target": "kids"},
"education_____help___deti.svg": {"category": "education", "keywords": "help", "target": "kids"},
"hygene_____wash_body___dorosli.svg": {"category": "hygiene", "keywords": "wash body", "target": "adults"},
"pandemics_____go_to_hospital___dorosli.svg": {"category": "pandemics", "keywords": "go to hospital", "target": "adults"},
"emotions_____sad___deti.svg": {"category": "emotions", "keywords": "sad", "target": "kids"},
"food_meals_____candy___deti.png": {"category": "food meals", "keywords": "candy", "target": "kids"},
"family_____brother___dorosli.svg": {"category": "family", "keywords": "brother", "target": "adults"},
"pandemics_____desinfect___dorosli.svg": {"category": "pandemics", "keywords": "desinfect", "target": "adults"},
"education_____paint___deti.svg": {"category": "education", "keywords": "paint", "target": "kids"},
"actions_____dress___deti.svg": {"category": "actions", "keywords": "dress", "target": "kids"},
"pronouns_____when___dorosli.svg": {"category": "pronouns", "keywords": "when", "target": "adults"},
"hygene_____wipe___dorosli.svg": {"category": "hygiene", "keywords": "wipe", "target": "adults"},
"family_____brother___deti.svg": {"category": "family", "keywords": "brother", "target": "kids"},
"numbers_quantity_____many___deti.svg": {"category": "numbers quantity", "keywords": "many", "target": "kids"},
"actions_____show___dorosli.svg": {"category": "actions", "keywords": "show", "target": "adults"},
"pandemics_____dizzy___dorosli.svg": {"category": "pandemics", "keywords": "dizzy", "target": "adults"},
"pandemics_____stay_home___dorosli.svg": {"category": "pandemics", "keywords": "stay home", "target": "adults"},
"family_____grandmother___dorosli.svg": {"category": "family", "keywords": "grandmother", "target": "adults"},
"family_____sister___deti.svg": {"category": "family", "keywords": "sister", "target": "kids"},
"pronouns_____who___dorosli.svg": {"category": "pronouns", "keywords": "who", "target": "adults"},
"actions_____like___dorosli.svg": {"category": "actions", "keywords": "like", "target": "adults"},
"communication_____do_not_want___dorosli.svg": {"category": "communication", "keywords": "do not want", "target": "adults"},
"holidays_____father_cristmas___deti.svg": {"category": "holidays", "keywords": "father cristmas", "target": "kids"},
"food_meals_____tea___deti.png": {"category": "food meals", "keywords": "tea", "target": "kids"},
"pandemics_____phone___dorosli.svg": {"category": "pandemics", "keywords": "phone", "target": "adults"},
"pronouns_____my___deti.svg": {"category": "pronouns", "keywords": "my", "target": "kids"},
"pandemics_____mask___dorosli.svg": {"category": "pandemics", "keywords": "mask", "target": "adults"},
"emotions_____angry___dorosli.svg": {"category": "emotions", "keywords": "angry", "target": "adults"},
"hygene_____brush_teeth___dorosli.svg": {"category": "hygiene", "keywords": "brush teeth", "target": "adults"},
"communication_____want___dorosli.svg": {"category": "communication", "keywords": "want", "target": "adults"},
"numbers_quantity_____few___dorosli.svg": {"category": "numbers quantity", "keywords": "few", "target": "adults"},
"family_____woman___dorosli.svg": {"category": "family", "keywords": "woman", "target": "adults"},
"education_____kindergarten___deti.svg": {"category": "education", "keywords": "kindergarten", "target": "kids"},
"food_meals_____milk___deti.png": {"category": "food meals", "keywords": "milk", "target": "kids"},
"holidays_____music___deti.svg": {"category": "holidays", "keywords": "music", "target": "kids"},
"emotions_____do_not_love___deti.svg": {"category": "emotions", "keywords": "do not love", "target": "kids"},
"health_____healthy___deti.svg": {"category": "health", "keywords": "healthy", "target": "kids"},
"family_____grandfather___deti.svg": {"category": "family", "keywords": "grandfather", "target": "kids"},
"communication_____you_may___deti.svg": {"category": "communication", "keywords": "you may", "target": "kids"},
"education_____read___deti.svg": {"category": "education", "keywords": "read", "target": "kids"},
"adjectives_____heavy___deti.svg": {"category": "adjectives", "keywords": "heavy", "target": "kids"},
"emotions_____calm___dorosli.svg": {"category": "emotions", "keywords": "calm", "target": "adults"},
"communication_____yes___deti.svg": {"category": "communication", "keywords": "yes", "target": "kids"},
"adjectives_____smooth___deti.svg": {"category": "adjectives", "keywords": "smooth", "target": "kids"},
"signals_____go_to_hospital___deti.svg": {"category": "signals", "keywords": "go to hospital", "target": "kids"},
"emotions_____want___deti.svg": {"category": "emotions", "keywords": "want", "target": "kids"},
"numbers_quantity_____four___deti.svg": {"category": "numbers quantity", "keywords": "four", "target": "kids"},
"numbers_quantity_____two___deti.svg": {"category": "numbers quantity", "keywords": "two", "target": "kids"},
"family_____son___dorosli.svg": {"category": "family", "keywords": "son", "target": "adults"},
"actions_____ask___deti.svg": {"category": "actions", "keywords": "ask", "target": "kids"},
"pandemics_____safe_distance___dorosli.svg": {"category": "pandemics", "keywords": "safe distance", "target": "adults"},
"actions_____run___deti.svg": {"category": "actions", "keywords": "run", "target": "kids"},
"numbers_quantity_____six___deti.svg": {"category": "numbers quantity", "keywords": "six", "target": "kids"},
"numbers_quantity_____zero___deti.svg": {"category": "numbers quantity", "keywords": "zero", "target": "kids"},
"actions_____take_off___deti.svg": {"category": "actions", "keywords": "take off", "target": "kids"},
"communication_____attention___deti.svg": {"category": "communication", "keywords": "attention", "target": "kids"},
"food_meals_____compot___deti.png": {"category": "food meals", "keywords": "juice", "target": "kids"},
"pronouns_____we___dorosli.svg": {"category": "pronouns", "keywords": "we", "target": "adults"},
"household_____products___dorosli.svg": {"category": "household", "keywords": "products", "target": "adults"},
"pandemics_____what_happened___dorosli.svg": {"category": "pandemics", "keywords": "what happened", "target": "adults"},
"signals_____dangereous___deti.svg": {"category": "signals", "keywords": "dangereous", "target": "kids"},
"numbers_quantity_____ten___deti.svg": {"category": "numbers quantity", "keywords": "ten", "target": "kids"},
"household_____utility_payments___dorosli.svg": {"category": "household", "keywords": "utility payments", "target": "adults"},
"household_____money___dorosli.svg": {"category": "household", "keywords": "money", "target": "adults"},
"pandemics_____blood_pressure___dorosli.svg": {"category": "pandemics", "keywords": "blood pressure", "target": "adults"},
"family_____mother___deti.svg": {"category": "family", "keywords": "mother", "target": "kids"},
"pandemics_____ill_people___dorosli.svg": {"category": "pandemics", "keywords": "ill people", "target": "adults"},
"adjectives_____dry___deti.svg": {"category": "adjectives", "keywords": "dry", "target": "kids"},
"actions_____go___deti.svg": {"category": "actions", "keywords": "go", "target": "kids"},
"emotions_____surprised___deti.svg": {"category": "emotions", "keywords": "surprised", "target": "kids"},
"actions_____drink___deti.svg": {"category": "actions", "keywords": "drink", "target": "kids"},
"education_____count___deti.svg": {"category": "education", "keywords": "count", "target": "kids"},
"pronouns_____your___deti.svg": {"category": "pronouns", "keywords": "your", "target": "kids"},
"household_____kitchen___deti.svg": {"category": "household", "keywords": "kitchen", "target": "kids"}
}

category_actions = {}
for path, data in cards.items():
    category = data["category"]
    action = data["keywords"]
    target = data["target"]
    if category not in category_actions:
        category_actions[category] = set()
    category_actions[category].add(action + " (" + target + ")")

cats = ""
for category, description in categories.items():
    actions = ", ".join(sorted(category_actions.get(category, [])))
    cats += f" - **{category}**: {description}"
    if actions:
        cats += f"; available keywords: {actions}\n"

print(cats)
