
categories = {
    "Household": "Cards related to daily activities and routine items",
    "Communication": "Cards for basic expressions, requests, and emotions",
    "Commands": "Cards for signals and instructions",
    "Meals": "Cards related to food items, flavors, and eating actions",
    "Clothes": "Cards related to clothing items and dressing actions",
    "Actions": "General action-oriented cards",
    "Pronouns": "Cards for pronouns",
    "Holiday": "Cards representing holiday-related activities and items",
    "Family": "Cards for family relationships",
    "Learning": "Cards for educational and school-related items and actions",
    "Pandemics": "Cards related to health safety during pandemics",
    "Health": "Cards for medical-related actions and items",
    "Numbers": "Cards related to numbers and quantities",
    "Hygiene": "Cards for hygiene routines",
    "Emotions": "Cards for emotional expressions",
    "Adjectives": "Cards with descriptive words"
}

cards = {
"./09 Household/household010_toys_00100deti.svg": {"category": "Household", "action": "toys", "target": "kids"},
"./09 Household/household010_shop_00290dorosli.svg": {"category": "Household", "action": "shop", "target": "adults"},
"./09 Household/household010_utility_payments_00287dorosli.svg": {"category": "Household", "action": "utility payments", "target": "adults"},
"./09 Household/household010_work_00286dorosli.svg": {"category": "Household", "action": "work", "target": "adults"},
"./09 Household/household010_products_00288dorosli.svg": {"category": "Household", "action": "products", "target": "adults"},
"./09 Household/household010_money_00289dorosli.svg": {"category": "Household", "action": "money", "target": "adults"},
"./09 Household/household010_kitchen_00102deti.svg": {"category": "Household", "action": "kitchen", "target": "kids"},
"./14 Communication/emotions002_I_do_not_want_00168deti.svg": {"category": "Communication", "action": "do not want", "target": "kids"},
"./14 Communication/communication011_do_not_want_00221dorosli.svg": {"category": "Communication", "action": "do not want", "target": "adults"},
"./14 Communication/communication011_yes_00105deti.svg": {"category": "Communication", "action": "yes", "target": "kids"},
"./14 Communication/communication011_great_00107deti.svg": {"category": "Communication", "action": "great", "target": "kids"},
"./14 Communication/communication011_yes_00223dorosli.svg": {"category": "Communication", "action": "yes", "target": "adults"},
"./14 Communication/pronouns015_me_00227dorosli.svg": {"category": "Pronouns", "action": "me", "target": "adults"},
"./14 Communication/communication011_no_00224dorosli.svg": {"category": "Communication", "action": "no", "target": "adults"},
"./14 Communication/communication011_bad_00226dorosli.svg": {"category": "Communication", "action": "bad", "target": "adults"},
"./14 Communication/communication011_you_may_00108deti.svg": {"category": "Communication", "action": "you may", "target": "kids"},
"./14 Communication/communication011_thank_you_00114deti.svg": {"category": "Communication", "action": "thank you", "target": "kids"},
"./14 Communication/communication011_stop_00110deti.svg": {"category": "Communication", "action": "stop", "target": "kids"},
"./14 Communication/communication011_communicate_00113deti.svg": {"category": "Communication", "action": "communicate", "target": "kids"},
"./14 Communication/communication011_wait_00111deti.svg": {"category": "Communication", "action": "wait", "target": "kids"},
"./14 Communication/communication011_good_00225dorosli.svg": {"category": "Communication", "action": "good", "target": "adults"},
"./14 Communication/communication011_bye_00104deti.svg": {"category": "Communication", "action": "bye", "target": "kids"},
"./14 Communication/communication011_want_00220dorosli.svg": {"category": "Communication", "action": "want", "target": "adults"},
"./14 Communication/emotions002_I_want_00167deti.svg": {"category": "Communication", "action": "want", "target": "kids"},
"./14 Communication/communication011_give_00222dorosli.svg": {"category": "Communication", "action": "give", "target": "adults"},
"./14 Communication/communication011_do_not_understand_00228dorosli.svg": {"category": "Communication", "action": "do not understand", "target": "adults"},
"./14 Communication/communication011_hello_00103deti.svg": {"category": "Communication", "action": "hello", "target": "kids"},
"./14 Communication/communication011_no_00106deti.svg": {"category": "Communication", "action": "no", "target": "kids"},
"./14 Communication/communication011_attention_00112deti.svg": {"category": "Communication", "action": "attention", "target": "kids"},
"./14 Communication/communication011_not_allowed_00109deti.svg": {"category": "Communication", "action": "not allowed", "target": "kids"},
"./12 Commands, signals/signals018_do_not_touch_00166deti.svg": {"category": "Commands,", "action": "do not touch", "target": "kids"},
"./12 Commands, signals/signals018_stop!_00162deti.svg": {"category": "Commands,", "action": "stop", "target": "kids"},
"./12 Commands, signals/signals018_go_to_hospital_00164deti.svg": {"category": "Commands,", "action": "go to hospital", "target": "kids"},
"./12 Commands, signals/signals018_dangereous_00165deti.svg": {"category": "Commands,", "action": "dangereous", "target": "kids"},
"./12 Commands, signals/signals018_call_my_family_00163deti.svg": {"category": "Commands,", "action": "call my family", "target": "kids"},
"./12 Commands, signals/signals018_get_back!_00161deti.svg": {"category": "Commands,", "action": "get back", "target": "kids"},
"./16 Meals/food_meals005_soup_00037deti.png": {"category": "Meals", "action": "soup", "target": "kids"},
"./16 Meals/food_meals005_milk_00041deti.png": {"category": "Meals", "action": "milk", "target": "kids"},
"./16 Meals/food_meals005_candy_00045deti.png": {"category": "Meals", "action": "candy", "target": "kids"},
"./16 Meals/food_meals005_compot_00040deti.png": {"category": "Meals", "action": "compot", "target": "kids"},
"./16 Meals/food_meals005_sour_00128deti.svg": {"category": "Meals", "action": "sour", "target": "kids"},
"./16 Meals/food_meals005_cereals_00038deti.png": {"category": "Meals", "action": "cereals", "target": "kids"},
"./16 Meals/food_meals005_eat_00046deti.svg": {"category": "Meals", "action": "eat", "target": "kids"},
"./16 Meals/food_meals005_bitter_00205dorosli.svg": {"category": "Meals", "action": "bitter", "target": "adults"},
"./16 Meals/food_meals005_salt_00127deti.svg": {"category": "Meals", "action": "salt", "target": "kids"},
"./16 Meals/food_meals005_tea_00039deti.png": {"category": "Meals", "action": "tea", "target": "kids"},
"./16 Meals/food_meals005_sweet_00126deti.svg": {"category": "Meals", "action": "sweet", "target": "kids"},
"./07 Clothes/actions006_take_off_00055deti.svg": {"category": "Clothes", "action": "take off", "target": "kids"},
"./07 Clothes/clothes006_clothes_00063deti.svg": {"category": "Clothes", "action": "clothes", "target": "kids"},
"./02 Actions/actions009_listen_00118deti.svg": {"category": "Actions", "action": "listen", "target": "kids"},
"./02 Actions/actions009_can_00083deti.svg": {"category": "Actions", "action": "can", "target": "kids"},
"./02 Actions/actions009_drink_00047deti.svg": {"category": "Actions", "action": "drink", "target": "kids"},
"./02 Actions/actions009_dress_00056deti.svg": {"category": "Actions", "action": "dress", "target": "kids"},
"./02 Actions/actions009_jamp_00122deti.svg": {"category": "Actions", "action": "jamp", "target": "kids"},
"./02 Actions/actions009_like_00176dorosli.svg": {"category": "Actions", "action": "like", "target": "adults"},
"./02 Actions/actions009_sit_00090deti.svg": {"category": "Actions", "action": "sit", "target": "kids"},
"./02 Actions/actions009_eat_00169dorosli.svg": {"category": "Actions", "action": "eat", "target": "adults"},
"./02 Actions/actions009_look_00094deti.svg": {"category": "Actions", "action": "look", "target": "kids"},
"./02 Actions/actions009_can_not_00084deti.svg": {"category": "Actions", "action": "can not", "target": "kids"},
"./02 Actions/actions009_gather_00096deti.svg": {"category": "Actions", "action": "gather", "target": "kids"},
"./02 Actions/actions009_go_00089deti.svg": {"category": "Actions", "action": "go", "target": "kids"},
"./02 Actions/actions009_dance_00117deti.svg": {"category": "Actions", "action": "dance", "target": "kids"},
"./02 Actions/actions009_clean_00095deti.svg": {"category": "Actions", "action": "clean", "target": "kids"},
"./02 Actions/actions009_go_00174dorosli.svg": {"category": "Actions", "action": "go", "target": "adults"},
"./02 Actions/actions009_run_00121deti.svg": {"category": "Actions", "action": "run", "target": "kids"},
"./02 Actions/actions009_walk_00097deti.svg": {"category": "Actions", "action": "walk", "target": "kids"},
"./02 Actions/actions009_take_00088deti.svg": {"category": "Actions", "action": "take", "target": "kids"},
"./02 Actions/actions009_speak_00093deti.svg": {"category": "Actions", "action": "speak", "target": "kids"},
"./02 Actions/actions009_drink_00170dorosli.svg": {"category": "Actions", "action": "drink", "target": "adults"},
"./02 Actions/actions009_show_00115deti.svg": {"category": "Actions", "action": "show", "target": "kids"},
"./02 Actions/actions009_do not like_00177dorosli.svg": {"category": "Actions", "action": "do not like", "target": "adults"},
"./02 Actions/actions009_rest_00120deti.svg": {"category": "Actions", "action": "rest", "target": "kids"},
"./02 Actions/actions009_lay_00171dorosli.svg": {"category": "Actions", "action": "lay", "target": "adults"},
"./02 Actions/actions009_talk_00172dorosli.svg": {"category": "Actions", "action": "talk", "target": "adults"},
"./02 Actions/actions009_lay_00091deti.svg": {"category": "Actions", "action": "lay", "target": "kids"},
"./02 Actions/actions009_sit_00173dorosli.svg": {"category": "Actions", "action": "sit", "target": "adults"},
"./02 Actions/actions009_give_00087deti.svg": {"category": "Actions", "action": "give", "target": "kids"},
"./02 Actions/actions009_dance_00119deti.svg": {"category": "Actions", "action": "dance", "target": "kids"},
"./02 Actions/actions009_show_00175dorosli.svg": {"category": "Actions", "action": "show", "target": "adults"},
"./02 Actions/actions009_ask_00116deti.svg": {"category": "Actions", "action": "ask", "target": "kids"},
"./02 Actions/actions009_play_00092deti.svg": {"category": "Actions", "action": "play", "target": "kids"},
"./04 Prenoms/pronouns015_we_00190dorosli.svg": {"category": "Pronouns", "action": "we", "target": "adults"},
"./04 Prenoms/pronouns015_who_00283dorosli.svg": {"category": "Pronouns", "action": "who", "target": "adults"},
"./04 Prenoms/pronouns015_how_00280dorosli.svg": {"category": "Pronouns", "action": "how", "target": "adults"},
"./04 Prenoms/pronouns015_I_00001deti.svg": {"category": "Pronouns", "action": "I", "target": "kids"},
"./04 Prenoms/pronouns015_me_00227dorosli.svg": {"category": "Pronouns", "action": "me", "target": "adults"},
"./04 Prenoms/family015_you_00008deti.svg": {"category": "Pronouns", "action": "you", "target": "kids"},
"./04 Prenoms/pronouns015_my_00147deti.svg": {"category": "Pronouns", "action": "my", "target": "kids"},
"./04 Prenoms/pronouns015_when_00284dorosli.svg": {"category": "Pronouns", "action": "when", "target": "adults"},
"./04 Prenoms/pronouns015_your_00148deti.svg": {"category": "Pronouns", "action": "your", "target": "kids"},
"./04 Prenoms/pronouns015_where_00285dorosli.svg": {"category": "Pronouns", "action": "where", "target": "adults"},
"./04 Prenoms/pronouns015_their_00150deti.svg": {"category": "Pronouns", "action": "their", "target": "kids"},
"./04 Prenoms/pronouns015_our_00149deti.svg": {"category": "Pronouns", "action": "our", "target": "kids"},
"./11 Holiday/holidays007_decorate_00061deti.svg": {"category": "Holiday", "action": "decorate", "target": "kids"},
"./11 Holiday/holidays007_greet_00065deti.svg": {"category": "Holiday", "action": "greet", "target": "kids"},
"./11 Holiday/holidays007_surprise_00066deti.svg": {"category": "Holiday", "action": "surprise", "target": "kids"},
"./11 Holiday/holidays007_new_year_tree_00057deti.svg": {"category": "Holiday", "action": "new year tree", "target": "kids"},
"./11 Holiday/holidays007_santa_claus_00059deti.svg": {"category": "Holiday", "action": "santa claus", "target": "kids"},
"./11 Holiday/holidays007_gift_00058deti.svg": {"category": "Holiday", "action": "gift", "target": "kids"},
"./11 Holiday/holidays007_music_00062deti.svg": {"category": "Holiday", "action": "music", "target": "kids"},
"./11 Holiday/holidays007_father_cristmas_00060deti.svg": {"category": "Holiday", "action": "father cristmas", "target": "kids"},
"./13 Family/family001_you_00189dorosli.svg": {"category": "Family", "action": "you", "target": "adults"},
"./13 Family/family001_I_00178dorosli.svg": {"category": "Family", "action": "I", "target": "adults"},
"./13 Family/family001_mother_00002deti.svg": {"category": "Family", "action": "mother", "target": "kids"},
"./13 Family/family001_daughter_00184dorosli.svg": {"category": "Family", "action": "daughter", "target": "adults"},
"./13 Family/family001_grandmother_00006deti.svg": {"category": "Family", "action": "grandmother", "target": "kids"},
"./13 Family/family001_grandmother_00187dorosli.svg": {"category": "Family", "action": "grandmother", "target": "adults"},
"./13 Family/family001_man_00181dorosli.svg": {"category": "Family", "action": "man", "target": "adults"},
"./13 Family/family001_sister_00186dorosli.svg": {"category": "Family", "action": "sister", "target": "adults"},
"./13 Family/family001_brother_00004deti.svg": {"category": "Family", "action": "brother", "target": "kids"},
"./13 Family/family001_woman_00180dorosli.svg": {"category": "Family", "action": "woman", "target": "adults"},
"./13 Family/family001_grandfather_00007deti.svg": {"category": "Family", "action": "grandfather", "target": "kids"},
"./13 Family/family001_sister_00005deti.svg": {"category": "Family", "action": "sister", "target": "kids"},
"./13 Family/family001_father_00003deti.svg": {"category": "Family", "action": "father", "target": "kids"},
"./13 Family/family001_son_00183dorosli.svg": {"category": "Family", "action": "son", "target": "adults"},
"./13 Family/family001_wife_00182dorosli.svg": {"category": "Family", "action": "wife", "target": "adults"},
"./13 Family/family001_grandfather_00188dorosli.svg": {"category": "Family", "action": "grandfather", "target": "adults"},
"./13 Family/family001_brother_00185dorosli.svg": {"category": "Family", "action": "brother", "target": "adults"},
"./13 Family/family001_man_00179dorosli.svg": {"category": "Family", "action": "man", "target": "adults"},
"./06 Learning/education008_school_00077deti.svg": {"category": "Learning", "action": "school", "target": "kids"},
"./06 Learning/education008_do_00082deti.svg": {"category": "Learning", "action": "do", "target": "kids"},
"./06 Learning/education008_must_00085deti.svg": {"category": "Learning", "action": "must", "target": "kids"},
"./06 Learning/education008_teacher(man)_00079deti.svg": {"category": "Learning", "action": "teacher (man)", "target": "kids"},
"./06 Learning/education008_answer_00073deti.svg": {"category": "Learning", "action": "answer", "target": "kids"},
"./06 Learning/education008_study_00067deti.svg": {"category": "Learning", "action": "study", "target": "kids"},
"./06 Learning/education008_paint_00074deti.svg": {"category": "Learning", "action": "paint", "target": "kids"},
"./06 Learning/education008_count_00071deti.svg": {"category": "Learning", "action": "count", "target": "kids"},
"./06 Learning/education008_get_calm_00068deti.svg": {"category": "Learning", "action": "get calm", "target": "kids"},
"./06 Learning/education008_kindergarten_00078deti.svg": {"category": "Learning", "action": "kindergarten", "target": "kids"},
"./06 Learning/education008_walk_00086deti.svg": {"category": "Learning", "action": "walk", "target": "kids"},
"./06 Learning/education008_break_00076deti.svg": {"category": "Learning", "action": "break", "target": "kids"},
"./06 Learning/education008_help_00075deti.svg": {"category": "Learning", "action": "help", "target": "kids"},
"./06 Learning/education008_read_00069deti.svg": {"category": "Learning", "action": "read", "target": "kids"},
"./06 Learning/education008_write_00070deti.svg": {"category": "Learning", "action": "write", "target": "kids"},
"./06 Learning/education008_teacher_(woman)_00080deti.svg": {"category": "Learning", "action": "teacher (woman)", "target": "kids"},
"./06 Learning/education008_ask_00072deti.svg": {"category": "Learning", "action": "ask", "target": "kids"},
"./06 Learning/education008_board_00081deti.svg": {"category": "Learning", "action": "board", "target": "kids"},
"./08 Pandemics/Pandemics030_ill_people_00263dorosli.svg": {"category": "Pandemics", "action": "ill people", "target": "adults"},
"./08 Pandemics/Pandemics030_dirty_hands_00267dorosli.svg": {"category": "Pandemics", "action": "dirty hands", "target": "adults"},
"./08 Pandemics/Pandemics030_wash_hands_00268dorosli.svg": {"category": "Pandemics", "action": "wash hands", "target": "adults"},
"./08 Pandemics/Pandemics030_blood_pressure_00278dorosli.svg": {"category": "Pandemics", "action": "blood pressure", "target": "adults"},
"./08 Pandemics/Pandemics030_hard_to_breathe_00276dorosli.svg": {"category": "Pandemics", "action": "hard to breathe", "target": "adults"},
"./08 Pandemics/Pandemics030_stay_in_bed_00279dorosli.svg": {"category": "Pandemics", "action": "stay in bed", "target": "adults"},
"./08 Pandemics/Pandemics030_desinfect_00269dorosli.svg": {"category": "Pandemics", "action": "desinfect", "target": "adults"},
"./08 Pandemics/Pandemics030_phone_00282dorosli.svg": {"category": "Pandemics", "action": "phone", "target": "adults"},
"./08 Pandemics/Pandemics030_mask_00270dorosli.svg": {"category": "Pandemics", "action": "mask", "target": "adults"},
"./08 Pandemics/Pandemics030_infected_00265dorosli.svg": {"category": "Pandemics", "action": "infected", "target": "adults"},
"./08 Pandemics/Pandemics030_quarantine_00272dorosli.svg": {"category": "Pandemics", "action": "quarantine", "target": "adults"},
"./08 Pandemics/Pandemics030_virus_00264dorosli.svg": {"category": "Pandemics", "action": "virus", "target": "adults"},
"./08 Pandemics/Pandemics030_go_to_hospital_00281dorosli.svg": {"category": "Pandemics", "action": "go to hospital", "target": "adults"},
"./08 Pandemics/Pandemics030_avoid_public_places_00274dorosli.svg": {"category": "Pandemics", "action": "avoid public places", "target": "adults"},
"./08 Pandemics/Pandemics030_dizzy_00277dorosli.svg": {"category": "Pandemics", "action": "dizzy", "target": "adults"},
"./08 Pandemics/Pandemics030_safe_distance_00271dorosli.svg": {"category": "Pandemics", "action": "safe distance", "target": "adults"},
"./08 Pandemics/Pandemics030_stay_home_00273dorosli.svg": {"category": "Pandemics", "action": "stay home", "target": "adults"},
"./08 Pandemics/Pandemics030_cough_00266dorosli.svg": {"category": "Pandemics", "action": "cough", "target": "adults"},
"./08 Pandemics/Pandemics030_what happened_00262dorosli.svg": {"category": "Pandemics", "action": "what happened", "target": "adults"},
"./08 Pandemics/Pandemics030_fever_00275dorosli.svg": {"category": "Pandemics", "action": "fever", "target": "adults"},
"./05 Health/health004_nurse_00215dorosli.svg": {"category": "Health", "action": "nurse", "target": "adults"},
"./05 Health/health004_fever_00033deti.svg": {"category": "Health", "action": "fever", "target": "kids"},
"./05 Health/health004_medicines_00036deti.svg": {"category": "Health", "action": "medicines", "target": "kids"},
"./05 Health/health004_ill_00028deti.svg": {"category": "Health", "action": "ill", "target": "kids"},
"./05 Health/health004_stay_at_hospital_00027dorosli.svg": {"category": "Health", "action": "stay at hospital", "target": "adults"},
"./05 Health/health004_body_temperature_00034deti.svg": {"category": "Health", "action": "body temperature", "target": "kids"},
"./05 Health/health004_injection_00035deti.svg": {"category": "Health", "action": "injection", "target": "kids"},
"./05 Health/health004_logoped_00216dorosli.svg": {"category": "Health", "action": "logoped", "target": "adults"},
"./05 Health/health004_healthy_00029deti.svg": {"category": "Health", "action": "healthy", "target": "kids"},
"./05 Health/health004_hurts_00214dorosli.svg": {"category": "Health", "action": "hurts", "target": "adults"},
"./05 Health/health004_doctor (woman)_00031deti.svg": {"category": "Health", "action": "doctor (woman)", "target": "kids"},
"./05 Health/health004_doctor(man)_00030deti.svg": {"category": "Health", "action": "doctor (man)", "target": "kids"},
"./05 Health/health004_hurts_00026deti.svg": {"category": "Health", "action": "hurts", "target": "kids"},
"./05 Health/health004_hospital_00032deti.svg": {"category": "Health", "action": "hospital", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_many_00152deti.svg": {"category": "Numbers", "action": "many", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_few_00255dorosli.svg": {"category": "Numbers", "action": "few", "target": "adults"},
"./17 Numbers. Quality/numbers_quantity014_several_00146deti.svg": {"category": "Numbers", "action": "several", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_zero_00145deti.svg": {"category": "Numbers", "action": "zero", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_four_00138deti.svg": {"category": "Numbers", "action": "four", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_two_00136deti.svg": {"category": "Numbers", "action": "two", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_ten_00144deti.svg": {"category": "Numbers", "action": "ten", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_a_little_00153deti.svg": {"category": "Numbers", "action": "a little", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_seven_00141deti.svg": {"category": "Numbers", "action": "seven", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_eight_00142deti.svg": {"category": "Numbers", "action": "eight", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_one_00135deti.svg": {"category": "Numbers", "action": "one", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_nine_00143deti.svg": {"category": "Numbers", "action": "nine", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_three_00137deti.svg": {"category": "Numbers", "action": "three", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_five_00139deti.svg": {"category": "Numbers", "action": "five", "target": "kids"},
"./17 Numbers. Quality/numbers_quantity014_six_00140deti.svg": {"category": "Numbers", "action": "six", "target": "kids"},
"./01 Hygiene/hygene003_wipe_00025deti.svg": {"category": "Hygiene", "action": "wipe", "target": "kids"},
"./01 Hygiene/hygene003_wash_face_00023deti.svg": {"category": "Hygiene", "action": "wash face", "target": "kids"},
"./01 Hygiene/hygene003_brush_teeth_00019deti.svg": {"category": "Hygiene", "action": "brush teeth", "target": "kids"},
"./01 Hygiene/hygene003_wash_body_00021deti.svg": {"category": "Hygiene", "action": "wash body", "target": "kids"},
"./01 Hygiene/hygene003_wipe_00212dorosli.svg": {"category": "Hygiene", "action": "wipe", "target": "adults"},
"./01 Hygiene/hygene003_toilet_00020deti.svg": {"category": "Hygiene", "action": "toilet", "target": "kids"},
"./01 Hygiene/hygene003_wash_face_00211dorosli.svg": {"category": "Hygiene", "action": "wash face", "target": "adults"},
"./01 Hygiene/hygene003_toilet_00213dorosli.svg": {"category": "Hygiene", "action": "toilet", "target": "adults"},
"./01 Hygiene/hygene003_brush_teeth_00208dorosli.svg": {"category": "Hygiene", "action": "brush teeth", "target": "adults"},
"./01 Hygiene/hygene003_wash_body_00207dorosli.svg": {"category": "Hygiene", "action": "wash body", "target": "adults"},
"./01 Hygiene/hygene003_wash_hands_00022deti.svg": {"category": "Hygiene", "action": "wash hands", "target": "kids"},
"./01 Hygiene/hygene003_wash_hands_00206dorosli.svg": {"category": "Hygiene", "action": "wash hands", "target": "adults"},
"./01 Hygiene/hygene003_rinse_mouth_00024deti.svg": {"category": "Hygiene", "action": "rinse mouth", "target": "kids"},
"./01 Hygiene/hygene003_rinse_mouth_00209dorosli.svg": {"category": "Hygiene", "action": "rinse mouth", "target": "adults"},
"./01 Hygiene/hygene003_comb_hair_00210dorosli.svg": {"category": "Hygiene", "action": "comb hair", "target": "adults"},
"./03 Emotions/emotions002_sad_00258dorosli.svg": {"category": "Emotions", "action": "sad", "target": "adults"},
"./03 Emotions/emotions002_I_don_t_want_00168deti.svg": {"category": "Emotions", "action": "do not want", "target": "kids"},
"./03 Emotions/emotions002_do_not_like_00018deti.svg": {"category": "Emotions", "action": "do not like", "target": "kids"},
"./03 Emotions/emotions002_love_00014deti.svg": {"category": "Emotions", "action": "love", "target": "kids"},
"./03 Emotions/emotions002_do_not_love_00015deti.svg": {"category": "Emotions", "action": "do not love", "target": "kids"},
"./03 Emotions/emotions002_tired_00016deti.svg": {"category": "Emotions", "action": "tired", "target": "kids"},
"./03 Emotions/emotions002_like_00017deti.svg": {"category": "Emotions", "action": "like", "target": "kids"},
"./03 Emotions/emotions002_joyful_00010deti.svg": {"category": "Emotions", "action": "joyful", "target": "kids"},
"./03 Emotions/emotions002_sad_00012deti.svg": {"category": "Emotions", "action": "sad", "target": "kids"},
"./03 Emotions/emotions002_angry_00011deti.svg": {"category": "Emotions", "action": "angry", "target": "kids"},
"./03 Emotions/emotions002_joyful_00257dorosli.svg": {"category": "Emotions", "action": "joyful", "target": "adults"},
"./03 Emotions/emotions002_I_want_00167deti.svg": {"category": "Emotions", "action": "want", "target": "kids"},
"./03 Emotions/emotions002_angry_00260dorosli.svg": {"category": "Emotions", "action": "angry", "target": "adults"},
"./03 Emotions/emotions002_tired_00259dorosli.svg": {"category": "Emotions", "action": "tired", "target": "adults"},
"./03 Emotions/emotions002_surprised_00013deti.svg": {"category": "Emotions", "action": "surprised", "target": "kids"},
"./03 Emotions/emotions002_calm_00261dorosli.svg": {"category": "Emotions", "action": "calm", "target": "adults"},
"./03 Emotions/emotions002_frightened_00009deti.svg": {"category": "Emotions", "action": "frightened", "target": "kids"},
"./10 Adjectives/adjectives013_cold_00123deti.svg": {"category": "Adjectives", "action": "cold", "target": "kids"},
"./10 Adjectives/adjectives013_dry_00129deti.svg": {"category": "Adjectives", "action": "dry", "target": "kids"},
"./10 Adjectives/adjectives013_smooth_00132deti.svg": {"category": "Adjectives", "action": "smooth", "target": "kids"},
"./10 Adjectives/adjectives013_younger_00133deti.svg": {"category": "Adjectives", "action": "younger", "target": "kids"},
"./10 Adjectives/adjectives013_wet_00130deti.svg": {"category": "Adjectives", "action": "wet", "target": "kids"},
"./10 Adjectives/adjectives013_older_00134deti.svg": {"category": "Adjectives", "action": "older", "target": "kids"},
"./10 Adjectives/adjectives013_heavy_00125deti.svg": {"category": "Adjectives", "action": "heavy", "target": "kids"},
"./10 Adjectives/adjectives013_common_00151deti.svg": {"category": "Adjectives", "action": "common", "target": "kids"},
"./10 Adjectives/adjectives013_light_00256dorosli.svg": {"category": "Adjectives", "action": "light", "target": "adults"},
"./10 Adjectives/adjectives013_hot_00124deti.svg": {"category": "Adjectives", "action": "hot", "target": "kids"},
"./10 Adjectives/adjectives013_barbed_00131deti.svg": {"category": "Adjectives", "action": "barbed", "target": "kids"}
}
